### PR TITLE
WIP: Add a new ResamplerTimer that is attached to the wall clock

### PR DESCRIPTION
**Pull request by llucax**
This is a new timer that is attached to the wall clock and can be used to trigger resampling windows. It is a replacement for the channels Timer class that was attached to the monotonic clock.

This should fix the issue with the resampling windows being too small when the system clock is not in sync with the wall clock.

### CODE REVIEW

**Comment by matthias-wende-frequenz** [comment]
@llucax what's the status here?

**Comment by llucax** [comment]
Nothing changed. I need to clean this up, and probably move the wall clock timer to the channels repo.

So much to do, so little time...

We could close the PR to reduce the noise, as I don't plan to work on it in the short term unless it becomes a *thing* again, my last understanding was that this almost never happens and that's why the priority was lowered.

**Comment by matthias-wende-frequenz** [comment]
I'd keep it open as I fear if we close it now, we will never do it. Let me take the issues back and I'll try to squeeze it in ;).

**Comment by llucax** [comment]
I will move the discussion to the original PR so it is move visible.

**Comment by llucax** [comment]
Closing in favor of https://github.com/frequenz-floss/frequenz-sdk-python/pull/999.

**Pull request closed without merging**
